export const SIGN_IN = "SIGN_IN";
export const GET_USER = "GET_USER";
export const GET_USER_FAILED = "GET_USER_FAILED";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const SIGN_IN_WITH_GOOGLE = "SIGN_IN_WITH_GOOGLE";
export const SIGN_IN_WITH_GOOGLE_FAILED = "SIGN_IN_WITH_GOOGLE_FAILED";
export const SIGN_IN_WITH_GOOGLE_SUCCESS = "SIGN_IN_WITH_GOOGLE_SUCCESS";

export const GET_ALL_BOOKS = "GET_ALL_BOOKS";
export const GET_BOOKS_SLIDE = "GET_BOOKS_SLIDE";
export const GET_BOOKS_SLIDE_SUCCESS = "GET_BOOKS_SLIDE_SUCCESS";
export const GET_BOOKS_SLIDE_FAILED = "GET_BOOKS_SLIDE_FAILED";
export const GET_BOOKS_FOR_YOU = "GET_BOOKS_FOR_YOU";
export const GET_BOOKS_FOR_YOU_SUCCESS = "GET_BOOKS_FOR_YOU_SUCCESS";
export const GET_BOOKS_FOR_YOU_FAILED = "GET_BOOKS_FOR_YOU_FAILED";
export const GET_BOOKS_BY_TAGS = "GET_BOOKS_BY_TAGS";
export const GET_BOOKS_BY_TAGS_SUCCESS = "GET_BOOKS_BY_TAGS_SUCCESS";
export const GET_BOOKS_BY_TAGS_FAILED = "GET_BOOKS_BY_TAGS_FAILED";

export const GET_ALL_TAGS_BY_CATEGORIES = "GET_ALL_TAGS_BY_CATEGORIES";
export const GET_ALL_TAGS_BY_CATEGORIES_SUCCESS =
  "GET_ALL_TAGS_BY_CATEGORIES_SUCCESS";
export const GET_ALL_TAGS_BY_CATEGORIES_FAILED =
  "GET_ALL_TAGS_BY_CATEGORIES_FAILED";

export const SIGN_OUT = "SIGN_OUT";
export const RE_SIGN = "RE_SIGN";
export const RE_SIGN_SUCCESS = "RE_SIGN_SUCCESS";
export const RE_SIGN_FAILED = "RE_SIGN_FAILED";

export const SNACK_BAR_OPEN = "SNACK_BAR_OPEN";
export const SNACK_BAR_CLOSE = "SNACK_BAR_CLOSE";
